services:
  - type: web
    name: ticket-booking-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ZhwzvRiaSTHJutpjaNcbGNRzhhshDUYn 